apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-dp
spec:
  replicas: 1
  template:
    metadata:
      name: mosquitto
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto-container
          image: luisavelino/iot-mosquitto:sem-autenticacao
          ports:
            - containerPort: 1883
          #envFrom:
          #  - secretRef:
          #      name: mosquitto-secret
  selector:
    matchLabels:
      app: mosquitto