version: '3.9'

services:                        
    influxdb:
        restart: always
        image: influxdb:1.8.3
        container_name: influxdb
        command: sh -c ./config/init.sh
        ports:
            - "8083:8083"
        networks:
            - production-network
        volumes:
            - influxdb-storage:/var/lib/influxdb

    telegraf:
        restart: always
        image: telegraf:latest
        container_name: telegraf
        links:
            - influxdb
        networks:
            - production-network
        volumes:
            - ./config/telegraf.conf:/etc/telegraf/telegraf.conf

    grafana:
        restart: always
        image: grafana/grafana:latest
        container_name: grafana
        ports:
                - "3000:3000"
        links:
            - influxdb
        depends_on:
            - influxdb
        networks:
            - production-network
        volumes:
            - ./config/grafana.ini:/etc/grafana/grafana.ini
            - grafana-storage:/var/lib/grafana

    mosquitto:
        restart: always
        image: eclipse-mosquitto
        hostname: mosquitto
        container_name: mosquitto
        ports:
            - "1883:1883"
        networks:
            - production-network
        volumes:
            - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
                    
volumes:
    influxdb-storage:
    grafana-storage:

networks:
    production-network:
        driver: bridge
