version: '3.3'

services:                        
    influxdb:
        restart: always
        image: luisavelino/iot-influxdb:1.0
        container_name: influxdb
        ports:
            - "8086:8086"
        networks:
            - production-network
        volumes:
            - influxdb-storage:/var/lib/influxdb

    telegraf:
        restart: always
        image: luisavelino/iot-telegraf:1.0
        container_name: telegraf
        links:
            - influxdb
        networks:
            - production-network

    grafana:
        restart: always
        image: luisavelino/iot-grafana:1.0
        container_name: grafana
        ports:
                - "3000:3000"
        links:
            - influxdb
        depends_on:
            - influxdb
        networks:
            - production-network
        volumes:
            - grafana-storage:/var/lib/grafana

    mosquitto:
        restart: always
        image: luisavelino/iot-mosquitto:1.0
        hostname: mosquitto
        container_name: mosquitto
        ports:
            - "1883:1883"
        networks:
            - production-network

volumes:
    influxdb-storage:
    grafana-storage:

networks:
    production-network:
        driver: bridge
